FROM golang:1.7

ADD . /go/src/github.com/openshift/online/force-sleep

RUN go install github.com/openshift/online/force-sleep/cmd/force-sleep

WORKDIR /go/src/github.com/openshift/online/force-sleep
ENTRYPOINT ["force-sleep"]